apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-message
  namespace: domain
data:
  index.html: |
    🙂 CoreDNS is configured to resolve services in the iximiuz.cluster zone.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: domain
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-content
        configMap:
          name: nginx-message
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: domain
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
